from time import time

from printable import Printable


class Block(Printable):
    """ a Single block of our blockchain.

    Attributes:
        index: The index of this block. 
        previous_hash: The hahs of the previous block in the blockchain.
        timestamp: The timestamp of the block (automatically generated by default)
        transactions: 
        proof: The proof of work number that yielded this block.
    """

    def __init__(self, index, previous_hash, transactions, proof, time=time()):
        self.index = index
        self.previous_hash = previous_hash
        self.timestamp = time
        self.transactions = transactions
        self.proof = proof
